package br.com.metashape.view;

import br.com.metashape.controle.ControleEstoque;
import br.com.metashape.produtos.Produto;
import br.com.metashape.produtos.ProdutoJaCadastradoException;
import br.com.metashape.produtos.ProdutoNaoEncontradoException;
import br.com.metashape.utils.DiretorioException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pedrobertolini
 */
public class CadastroProduto extends javax.swing.JInternalFrame {

   

    /**
     * Creates new form CadastroLoja
     */
    public CadastroProduto() {
        initComponents();       
  }
  

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        códigoSKU = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        qtdd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomeDoProduto = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        categoriaDropDown = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        saborCor = new javax.swing.JComboBox<>();
        valor = new javax.swing.JFormattedTextField();
        descricao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setOpaque(false);
        setRequestFocusEnabled(false);
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(códigoSKU, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 210, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Código SKU");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Valor");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quantidade");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));
        getContentPane().add(qtdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 210, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome do produto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));
        getContentPane().add(nomeDoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 210, -1));

        btnConfirmar.setBackground(new java.awt.Color(0, 204, 51));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 210, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setDisplayedMnemonic('C');
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CADASTRO PRODUTO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 200, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Categoria");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, -1));

        categoriaDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Whey", "Creatina", "Hiercalórico", "Termogênico" }));
        categoriaDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaDropDownActionPerformed(evt);
            }
        });
        getContentPane().add(categoriaDropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 210, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sabor / Cor");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, -1, -1));

        saborCor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem sabor", "Chocolate", "Morango", "Baunilha", "Cookies", "Cappuccino" }));
        saborCor.setToolTipText("");
        saborCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saborCorActionPerformed(evt);
            }
        });
        getContentPane().add(saborCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 210, -1));

        valor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorActionPerformed(evt);
            }
        });
        getContentPane().add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 210, 30));
        getContentPane().add(descricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 210, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Descrição");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg_4.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -30, 1050, 670));

        setBounds(0, 0, 1052, 669);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
            cadastrar();
        } catch (DiretorioException ex) {
            Logger.getLogger(CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void categoriaDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaDropDownActionPerformed

    private void saborCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saborCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saborCorActionPerformed

    private void valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox<String> categoriaDropDown;
    private javax.swing.JTextField códigoSKU;
    private javax.swing.JTextField descricao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nomeDoProduto;
    private javax.swing.JTextField qtdd;
    private javax.swing.JComboBox<String> saborCor;
    private javax.swing.JFormattedTextField valor;
    // End of variables declaration//GEN-END:variables
    private ControleEstoque controleEstoque;
    Produto n;
    private void cadastrar() throws DiretorioException {
        try {
            String sku = nomeDoProduto.getText();
            n = new Produto();
            n.setCod_sku(this.códigoSKU.getText());
            n.setAtivo(true);
            n.setCategoria(this.categoriaDropDown.getActionCommand());
            n.setSabor_cor(this.saborCor.getActionCommand());
            n.setNome_sku(this.nomeDoProduto.getText());
            n.setDescricao(this.descricao.getText());
            n.setValor(this.valor.getText());
            n.setQuantidade(Integer.parseInt(this.qtdd.getText()));
            try {
                controleEstoque.cadastrar(n);
            } catch (ProdutoNaoEncontradoException | ProdutoJaCadastradoException ex) {
                Logger.getLogger(CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (DiretorioException ex) {
            Logger.getLogger(CadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }finally {
            limparCampos();
        }
    }

    private void limparCampos() {
        this.códigoSKU.setText("");
        this.nomeDoProduto.setText("");
        this.categoriaDropDown.setSelectedIndex(1);
        this.descricao.setText("");
        this.qtdd.setText("");
        this.valor.setText("");

    }

}
