/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.metashape.view;

import br.com.metashape.controle.ControleEstoque;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.KeyStroke;
import javax.swing.WindowConstants;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author pedrobertolini
 */
public class InicialPage extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    
   private ControleEstoque cE;
    
    public InicialPage() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/image/ms-icon.png")).getImage());
        this.cE = new ControleEstoque();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new JLabel();
        txtConectadoComo = new JLabel();
        jLabel1 = new JLabel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/image/bg_4.jpg"));
        Image image = icon.getImage();
        jDesktopPane1 = new JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };
        jMenuBar1 = new JMenuBar();
        cadastrarLoja = new JMenu();
        jMenuItem1 = new JMenuItem();
        jMenuItem2 = new JMenuItem();
        jMenu4 = new JMenu();
        jMenuItem10 = new JMenuItem();
        jMenuItem11 = new JMenuItem();
        jMenu2 = new JMenu();
        jMenuItem4 = new JMenuItem();
        jMenuItem5 = new JMenuItem();
        jMenu5 = new JMenu();
        jMenuItem19 = new JMenuItem();
        jMenuItem21 = new JMenuItem();
        jMenu8 = new JMenu();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("MetaShape - Administrative");
        setBackground(new Color(24, 24, 24));
        setResizable(false);
        getContentPane().setLayout(new AbsoluteLayout());

        jLabel9.setIcon(new ImageIcon(getClass().getResource("/image/ms-icon.png"))); // NOI18N
        getContentPane().add(jLabel9, new AbsoluteConstraints(0, 330, 310, 320));

        txtConectadoComo.setBackground(new Color(255, 255, 255));
        txtConectadoComo.setForeground(new Color(255, 255, 255));
        txtConectadoComo.setText("Conectado como: ");
        getContentPane().add(txtConectadoComo, new AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new ImageIcon(getClass().getResource("/image/bg_4.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new AbsoluteConstraints(0, 0, 1050, 650));
        getContentPane().add(jDesktopPane1, new AbsoluteConstraints(1, 1, 1050, 650));

        cadastrarLoja.setIcon(new ImageIcon(getClass().getResource("/image/StoreIcon.png"))); // NOI18N
        cadastrarLoja.setText("Lojas");
        cadastrarLoja.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cadastrarLojaActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_N, InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new ImageIcon(getClass().getResource("/image/createIcon.png"))); // NOI18N
        jMenuItem1.setText("Cadastrar");
        jMenuItem1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        cadastrarLoja.add(jMenuItem1);

        jMenuItem2.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S, InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new ImageIcon(getClass().getResource("/image/searchIcon.png"))); // NOI18N
        jMenuItem2.setText("Buscar");
        jMenuItem2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        cadastrarLoja.add(jMenuItem2);

        jMenuBar1.add(cadastrarLoja);

        jMenu4.setIcon(new ImageIcon(getClass().getResource("/image/ProductIcon.png"))); // NOI18N
        jMenu4.setText("Produtos");

        jMenuItem10.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_N, InputEvent.CTRL_MASK));
        jMenuItem10.setIcon(new ImageIcon(getClass().getResource("/image/createIcon.png"))); // NOI18N
        jMenuItem10.setText("Cadastrar");
        jMenuItem10.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuItem11.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S, InputEvent.CTRL_MASK));
        jMenuItem11.setIcon(new ImageIcon(getClass().getResource("/image/searchIcon.png"))); // NOI18N
        jMenuItem11.setText("Buscar");
        jMenuItem11.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuBar1.add(jMenu4);

        jMenu2.setIcon(new ImageIcon(getClass().getResource("/image/ProfissionalIcon.png"))); // NOI18N
        jMenu2.setText("Treinadores / Nutricionistas / Funcionarios");

        jMenuItem4.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_N, InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new ImageIcon(getClass().getResource("/image/createIcon.png"))); // NOI18N
        jMenuItem4.setText("Cadastrar");
        jMenuItem4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S, InputEvent.CTRL_MASK));
        jMenuItem5.setIcon(new ImageIcon(getClass().getResource("/image/searchIcon.png"))); // NOI18N
        jMenuItem5.setText("Buscar");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu5.setIcon(new ImageIcon(getClass().getResource("/image/FinancialIcon.png"))); // NOI18N
        jMenu5.setText("Administrativo");

        jMenuItem19.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_E, InputEvent.CTRL_MASK));
        jMenuItem19.setIcon(new ImageIcon(getClass().getResource("/image/SubstoreIcon.png"))); // NOI18N
        jMenuItem19.setText("Estoque");
        jMenu5.add(jMenuItem19);

        jMenuItem21.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_B, InputEvent.CTRL_MASK));
        jMenuItem21.setIcon(new ImageIcon(getClass().getResource("/image/BalanceIcon.png"))); // NOI18N
        jMenuItem21.setText("Balanço");
        jMenu5.add(jMenuItem21);

        jMenuBar1.add(jMenu5);

        jMenu8.setIcon(new ImageIcon(getClass().getResource("/image/ExitIcon.png"))); // NOI18N
        jMenu8.setText("Sair");
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarLojaActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cadastrarLojaActionPerformed
        // TODO add your handling code here:        
        CadastroLoja telaCadLoja = new CadastroLoja(this.cE);
        jDesktopPane1.add(telaCadLoja);
        telaCadLoja.setVisible(true);

    }//GEN-LAST:event_cadastrarLojaActionPerformed

    private void jMenuItem1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        CadastroLoja telaCadLoja = new CadastroLoja(this.cE);
        jDesktopPane1.add(telaCadLoja);
        telaCadLoja.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem10ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        CadastroProduto telaCadProduto = new CadastroProduto(this.cE);
        jDesktopPane1.add(telaCadProduto);
        telaCadProduto.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem4ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        CadastroProfissional telaCadProfissional = new CadastroProfissional(this.cE);
        jDesktopPane1.add(telaCadProfissional);
        telaCadProfissional.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
       BuscarLoja telaBuscarLoja = new BuscarLoja(this.cE);
        jDesktopPane1.add(telaBuscarLoja);
        telaBuscarLoja.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem11ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        BuscarProduto telaBuscarProduto = new BuscarProduto(this.cE);
        jDesktopPane1.add(telaBuscarProduto);
        telaBuscarProduto.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicialPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicialPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicialPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicialPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicialPage().setVisible(true);
            }
        });
    }

    public void recebe(String nome){
        txtConectadoComo.setText("Conectado como: " + nome);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JMenu cadastrarLoja;
    private JDesktopPane jDesktopPane1;
    private JLabel jLabel1;
    private JLabel jLabel9;
    private JMenu jMenu2;
    private JMenu jMenu4;
    private JMenu jMenu5;
    private JMenu jMenu8;
    private JMenuBar jMenuBar1;
    private JMenuItem jMenuItem1;
    private JMenuItem jMenuItem10;
    private JMenuItem jMenuItem11;
    private JMenuItem jMenuItem19;
    private JMenuItem jMenuItem2;
    private JMenuItem jMenuItem21;
    private JMenuItem jMenuItem4;
    private JMenuItem jMenuItem5;
    private JLabel txtConectadoComo;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the nome
     */
  
}
